//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoCalculoDetenido.wcfGps {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wcfGps.IService1")]
    public interface IService1 {
        
        // CODEGEN: Generating message contract since element name SP_ListaDispositivosPosicionResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_ListaDispositivosPosicion", ReplyAction="http://tempuri.org/IService1/SP_ListaDispositivosPosicionResponse")]
        global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosPosicionResponse SP_ListaDispositivosPosicion(global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosPosicionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_ListaDispositivosPosicion", ReplyAction="http://tempuri.org/IService1/SP_ListaDispositivosPosicionResponse")]
        System.Threading.Tasks.Task<global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosPosicionResponse> SP_ListaDispositivosPosicionAsync(global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosPosicionRequest request);
        
        // CODEGEN: Generating message contract since element name SP_ListaDispositivosPosicionIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_ListaDispositivosPosicionId", ReplyAction="http://tempuri.org/IService1/SP_ListaDispositivosPosicionIdResponse")]
        global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosPosicionIdResponse SP_ListaDispositivosPosicionId(global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosPosicionIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_ListaDispositivosPosicionId", ReplyAction="http://tempuri.org/IService1/SP_ListaDispositivosPosicionIdResponse")]
        System.Threading.Tasks.Task<global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosPosicionIdResponse> SP_ListaDispositivosPosicionIdAsync(global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosPosicionIdRequest request);
        
        // CODEGEN: Generating message contract since element name SP_ListaDispositivosResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_ListaDispositivos", ReplyAction="http://tempuri.org/IService1/SP_ListaDispositivosResponse")]
        global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosResponse SP_ListaDispositivos(global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_ListaDispositivos", ReplyAction="http://tempuri.org/IService1/SP_ListaDispositivosResponse")]
        System.Threading.Tasks.Task<global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosResponse> SP_ListaDispositivosAsync(global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosRequest request);
        
        // CODEGEN: Generating message contract since element name SP_ListaDispositivosIDResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_ListaDispositivosID", ReplyAction="http://tempuri.org/IService1/SP_ListaDispositivosIDResponse")]
        global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosIDResponse SP_ListaDispositivosID(global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_ListaDispositivosID", ReplyAction="http://tempuri.org/IService1/SP_ListaDispositivosIDResponse")]
        System.Threading.Tasks.Task<global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosIDResponse> SP_ListaDispositivosIDAsync(global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosIDRequest request);
        
        // CODEGEN: Generating message contract since element name SP_GetColoresResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_GetColores", ReplyAction="http://tempuri.org/IService1/SP_GetColoresResponse")]
        global::demoCalculoDetenido.wcfGps.SP_GetColoresResponse SP_GetColores(global::demoCalculoDetenido.wcfGps.SP_GetColoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_GetColores", ReplyAction="http://tempuri.org/IService1/SP_GetColoresResponse")]
        System.Threading.Tasks.Task<global::demoCalculoDetenido.wcfGps.SP_GetColoresResponse> SP_GetColoresAsync(global::demoCalculoDetenido.wcfGps.SP_GetColoresRequest request);
        
        // CODEGEN: Generating message contract since element name SP_GetColoresIDResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_GetColoresID", ReplyAction="http://tempuri.org/IService1/SP_GetColoresIDResponse")]
        global::demoCalculoDetenido.wcfGps.SP_GetColoresIDResponse SP_GetColoresID(global::demoCalculoDetenido.wcfGps.SP_GetColoresIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_GetColoresID", ReplyAction="http://tempuri.org/IService1/SP_GetColoresIDResponse")]
        System.Threading.Tasks.Task<global::demoCalculoDetenido.wcfGps.SP_GetColoresIDResponse> SP_GetColoresIDAsync(global::demoCalculoDetenido.wcfGps.SP_GetColoresIDRequest request);
        
        // CODEGEN: Generating message contract since element name contrato from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WPL_POW_EntregaRetiro", ReplyAction="http://tempuri.org/IService1/WPL_POW_EntregaRetiroResponse")]
        global::demoCalculoDetenido.wcfGps.WPL_POW_EntregaRetiroResponse WPL_POW_EntregaRetiro(global::demoCalculoDetenido.wcfGps.WPL_POW_EntregaRetiroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WPL_POW_EntregaRetiro", ReplyAction="http://tempuri.org/IService1/WPL_POW_EntregaRetiroResponse")]
        System.Threading.Tasks.Task<global::demoCalculoDetenido.wcfGps.WPL_POW_EntregaRetiroResponse> WPL_POW_EntregaRetiroAsync(global::demoCalculoDetenido.wcfGps.WPL_POW_EntregaRetiroRequest request);
        
        // CODEGEN: Generating message contract since element name fechain from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_TraePosiciones", ReplyAction="http://tempuri.org/IService1/SP_TraePosicionesResponse")]
        global::demoCalculoDetenido.wcfGps.SP_TraePosicionesResponse SP_TraePosiciones(global::demoCalculoDetenido.wcfGps.SP_TraePosicionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_TraePosiciones", ReplyAction="http://tempuri.org/IService1/SP_TraePosicionesResponse")]
        System.Threading.Tasks.Task<global::demoCalculoDetenido.wcfGps.SP_TraePosicionesResponse> SP_TraePosicionesAsync(global::demoCalculoDetenido.wcfGps.SP_TraePosicionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_UpdateDispositivo", ReplyAction="http://tempuri.org/IService1/SP_UpdateDispositivoResponse")]
        string SP_UpdateDispositivo(int id, string nombre, string modelo, string patente, string imei, string numero, int activo, int color);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_UpdateDispositivo", ReplyAction="http://tempuri.org/IService1/SP_UpdateDispositivoResponse")]
        System.Threading.Tasks.Task<string> SP_UpdateDispositivoAsync(int id, string nombre, string modelo, string patente, string imei, string numero, int activo, int color);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_InsertaDispositivo", ReplyAction="http://tempuri.org/IService1/SP_InsertaDispositivoResponse")]
        string SP_InsertaDispositivo(string nombre, string modelo, string patente, string imei, string numero, int activo, int color);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_InsertaDispositivo", ReplyAction="http://tempuri.org/IService1/SP_InsertaDispositivoResponse")]
        System.Threading.Tasks.Task<string> SP_InsertaDispositivoAsync(string nombre, string modelo, string patente, string imei, string numero, int activo, int color);
        
        // CODEGEN: Generating message contract since element name SP_MarcaAlarmaResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_MarcaAlarma", ReplyAction="http://tempuri.org/IService1/SP_MarcaAlarmaResponse")]
        global::demoCalculoDetenido.wcfGps.SP_MarcaAlarmaResponse SP_MarcaAlarma(global::demoCalculoDetenido.wcfGps.SP_MarcaAlarmaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_MarcaAlarma", ReplyAction="http://tempuri.org/IService1/SP_MarcaAlarmaResponse")]
        System.Threading.Tasks.Task<global::demoCalculoDetenido.wcfGps.SP_MarcaAlarmaResponse> SP_MarcaAlarmaAsync(global::demoCalculoDetenido.wcfGps.SP_MarcaAlarmaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_InsertaPosicion", ReplyAction="http://tempuri.org/IService1/SP_InsertaPosicionResponse")]
        string SP_InsertaPosicion(string direccion, double altitud, double curso, double latitud, double longitud, string otros, int poder, double velocidad, System.DateTime fechahora, int valido, int dispositivo_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_InsertaPosicion", ReplyAction="http://tempuri.org/IService1/SP_InsertaPosicionResponse")]
        System.Threading.Tasks.Task<string> SP_InsertaPosicionAsync(string direccion, double altitud, double curso, double latitud, double longitud, string otros, int poder, double velocidad, System.DateTime fechahora, int valido, int dispositivo_id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SP_ListaDispositivosPosicionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SP_ListaDispositivosPosicion", Namespace="http://tempuri.org/", Order=0)]
        public global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosPosicionRequestBody Body;
        
        public SP_ListaDispositivosPosicionRequest() {
        }
        
        public SP_ListaDispositivosPosicionRequest(global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosPosicionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SP_ListaDispositivosPosicionRequestBody {
        
        public SP_ListaDispositivosPosicionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SP_ListaDispositivosPosicionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SP_ListaDispositivosPosicionResponse", Namespace="http://tempuri.org/", Order=0)]
        public global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosPosicionResponseBody Body;
        
        public SP_ListaDispositivosPosicionResponse() {
        }
        
        public SP_ListaDispositivosPosicionResponse(global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosPosicionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SP_ListaDispositivosPosicionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement SP_ListaDispositivosPosicionResult;
        
        public SP_ListaDispositivosPosicionResponseBody() {
        }
        
        public SP_ListaDispositivosPosicionResponseBody(System.Xml.Linq.XElement SP_ListaDispositivosPosicionResult) {
            this.SP_ListaDispositivosPosicionResult = SP_ListaDispositivosPosicionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SP_ListaDispositivosPosicionIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SP_ListaDispositivosPosicionId", Namespace="http://tempuri.org/", Order=0)]
        public global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosPosicionIdRequestBody Body;
        
        public SP_ListaDispositivosPosicionIdRequest() {
        }
        
        public SP_ListaDispositivosPosicionIdRequest(global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosPosicionIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SP_ListaDispositivosPosicionIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public SP_ListaDispositivosPosicionIdRequestBody() {
        }
        
        public SP_ListaDispositivosPosicionIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SP_ListaDispositivosPosicionIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SP_ListaDispositivosPosicionIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosPosicionIdResponseBody Body;
        
        public SP_ListaDispositivosPosicionIdResponse() {
        }
        
        public SP_ListaDispositivosPosicionIdResponse(global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosPosicionIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SP_ListaDispositivosPosicionIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement SP_ListaDispositivosPosicionIdResult;
        
        public SP_ListaDispositivosPosicionIdResponseBody() {
        }
        
        public SP_ListaDispositivosPosicionIdResponseBody(System.Xml.Linq.XElement SP_ListaDispositivosPosicionIdResult) {
            this.SP_ListaDispositivosPosicionIdResult = SP_ListaDispositivosPosicionIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SP_ListaDispositivosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SP_ListaDispositivos", Namespace="http://tempuri.org/", Order=0)]
        public global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosRequestBody Body;
        
        public SP_ListaDispositivosRequest() {
        }
        
        public SP_ListaDispositivosRequest(global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SP_ListaDispositivosRequestBody {
        
        public SP_ListaDispositivosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SP_ListaDispositivosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SP_ListaDispositivosResponse", Namespace="http://tempuri.org/", Order=0)]
        public global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosResponseBody Body;
        
        public SP_ListaDispositivosResponse() {
        }
        
        public SP_ListaDispositivosResponse(global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SP_ListaDispositivosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement SP_ListaDispositivosResult;
        
        public SP_ListaDispositivosResponseBody() {
        }
        
        public SP_ListaDispositivosResponseBody(System.Xml.Linq.XElement SP_ListaDispositivosResult) {
            this.SP_ListaDispositivosResult = SP_ListaDispositivosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SP_ListaDispositivosIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SP_ListaDispositivosID", Namespace="http://tempuri.org/", Order=0)]
        public global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosIDRequestBody Body;
        
        public SP_ListaDispositivosIDRequest() {
        }
        
        public SP_ListaDispositivosIDRequest(global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SP_ListaDispositivosIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public SP_ListaDispositivosIDRequestBody() {
        }
        
        public SP_ListaDispositivosIDRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SP_ListaDispositivosIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SP_ListaDispositivosIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosIDResponseBody Body;
        
        public SP_ListaDispositivosIDResponse() {
        }
        
        public SP_ListaDispositivosIDResponse(global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SP_ListaDispositivosIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement SP_ListaDispositivosIDResult;
        
        public SP_ListaDispositivosIDResponseBody() {
        }
        
        public SP_ListaDispositivosIDResponseBody(System.Xml.Linq.XElement SP_ListaDispositivosIDResult) {
            this.SP_ListaDispositivosIDResult = SP_ListaDispositivosIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SP_GetColoresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SP_GetColores", Namespace="http://tempuri.org/", Order=0)]
        public global::demoCalculoDetenido.wcfGps.SP_GetColoresRequestBody Body;
        
        public SP_GetColoresRequest() {
        }
        
        public SP_GetColoresRequest(global::demoCalculoDetenido.wcfGps.SP_GetColoresRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SP_GetColoresRequestBody {
        
        public SP_GetColoresRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SP_GetColoresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SP_GetColoresResponse", Namespace="http://tempuri.org/", Order=0)]
        public global::demoCalculoDetenido.wcfGps.SP_GetColoresResponseBody Body;
        
        public SP_GetColoresResponse() {
        }
        
        public SP_GetColoresResponse(global::demoCalculoDetenido.wcfGps.SP_GetColoresResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SP_GetColoresResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement SP_GetColoresResult;
        
        public SP_GetColoresResponseBody() {
        }
        
        public SP_GetColoresResponseBody(System.Xml.Linq.XElement SP_GetColoresResult) {
            this.SP_GetColoresResult = SP_GetColoresResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SP_GetColoresIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SP_GetColoresID", Namespace="http://tempuri.org/", Order=0)]
        public global::demoCalculoDetenido.wcfGps.SP_GetColoresIDRequestBody Body;
        
        public SP_GetColoresIDRequest() {
        }
        
        public SP_GetColoresIDRequest(global::demoCalculoDetenido.wcfGps.SP_GetColoresIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SP_GetColoresIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public SP_GetColoresIDRequestBody() {
        }
        
        public SP_GetColoresIDRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SP_GetColoresIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SP_GetColoresIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public global::demoCalculoDetenido.wcfGps.SP_GetColoresIDResponseBody Body;
        
        public SP_GetColoresIDResponse() {
        }
        
        public SP_GetColoresIDResponse(global::demoCalculoDetenido.wcfGps.SP_GetColoresIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SP_GetColoresIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement SP_GetColoresIDResult;
        
        public SP_GetColoresIDResponseBody() {
        }
        
        public SP_GetColoresIDResponseBody(System.Xml.Linq.XElement SP_GetColoresIDResult) {
            this.SP_GetColoresIDResult = SP_GetColoresIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WPL_POW_EntregaRetiroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WPL_POW_EntregaRetiro", Namespace="http://tempuri.org/", Order=0)]
        public global::demoCalculoDetenido.wcfGps.WPL_POW_EntregaRetiroRequestBody Body;
        
        public WPL_POW_EntregaRetiroRequest() {
        }
        
        public WPL_POW_EntregaRetiroRequest(global::demoCalculoDetenido.wcfGps.WPL_POW_EntregaRetiroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WPL_POW_EntregaRetiroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string contrato;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string rut;
        
        public WPL_POW_EntregaRetiroRequestBody() {
        }
        
        public WPL_POW_EntregaRetiroRequestBody(string contrato, string rut) {
            this.contrato = contrato;
            this.rut = rut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WPL_POW_EntregaRetiroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WPL_POW_EntregaRetiroResponse", Namespace="http://tempuri.org/", Order=0)]
        public global::demoCalculoDetenido.wcfGps.WPL_POW_EntregaRetiroResponseBody Body;
        
        public WPL_POW_EntregaRetiroResponse() {
        }
        
        public WPL_POW_EntregaRetiroResponse(global::demoCalculoDetenido.wcfGps.WPL_POW_EntregaRetiroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WPL_POW_EntregaRetiroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement WPL_POW_EntregaRetiroResult;
        
        public WPL_POW_EntregaRetiroResponseBody() {
        }
        
        public WPL_POW_EntregaRetiroResponseBody(System.Xml.Linq.XElement WPL_POW_EntregaRetiroResult) {
            this.WPL_POW_EntregaRetiroResult = WPL_POW_EntregaRetiroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SP_TraePosicionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SP_TraePosiciones", Namespace="http://tempuri.org/", Order=0)]
        public global::demoCalculoDetenido.wcfGps.SP_TraePosicionesRequestBody Body;
        
        public SP_TraePosicionesRequest() {
        }
        
        public SP_TraePosicionesRequest(global::demoCalculoDetenido.wcfGps.SP_TraePosicionesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SP_TraePosicionesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fechain;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fechaout;
        
        public SP_TraePosicionesRequestBody() {
        }
        
        public SP_TraePosicionesRequestBody(int id, string fechain, string fechaout) {
            this.id = id;
            this.fechain = fechain;
            this.fechaout = fechaout;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SP_TraePosicionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SP_TraePosicionesResponse", Namespace="http://tempuri.org/", Order=0)]
        public global::demoCalculoDetenido.wcfGps.SP_TraePosicionesResponseBody Body;
        
        public SP_TraePosicionesResponse() {
        }
        
        public SP_TraePosicionesResponse(global::demoCalculoDetenido.wcfGps.SP_TraePosicionesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SP_TraePosicionesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement SP_TraePosicionesResult;
        
        public SP_TraePosicionesResponseBody() {
        }
        
        public SP_TraePosicionesResponseBody(System.Xml.Linq.XElement SP_TraePosicionesResult) {
            this.SP_TraePosicionesResult = SP_TraePosicionesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SP_MarcaAlarmaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SP_MarcaAlarma", Namespace="http://tempuri.org/", Order=0)]
        public global::demoCalculoDetenido.wcfGps.SP_MarcaAlarmaRequestBody Body;
        
        public SP_MarcaAlarmaRequest() {
        }
        
        public SP_MarcaAlarmaRequest(global::demoCalculoDetenido.wcfGps.SP_MarcaAlarmaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SP_MarcaAlarmaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public SP_MarcaAlarmaRequestBody() {
        }
        
        public SP_MarcaAlarmaRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SP_MarcaAlarmaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SP_MarcaAlarmaResponse", Namespace="http://tempuri.org/", Order=0)]
        public global::demoCalculoDetenido.wcfGps.SP_MarcaAlarmaResponseBody Body;
        
        public SP_MarcaAlarmaResponse() {
        }
        
        public SP_MarcaAlarmaResponse(global::demoCalculoDetenido.wcfGps.SP_MarcaAlarmaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SP_MarcaAlarmaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement SP_MarcaAlarmaResult;
        
        public SP_MarcaAlarmaResponseBody() {
        }
        
        public SP_MarcaAlarmaResponseBody(System.Xml.Linq.XElement SP_MarcaAlarmaResult) {
            this.SP_MarcaAlarmaResult = SP_MarcaAlarmaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : global::demoCalculoDetenido.wcfGps.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<global::demoCalculoDetenido.wcfGps.IService1>, global::demoCalculoDetenido.wcfGps.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosPosicionResponse global::demoCalculoDetenido.wcfGps.IService1.SP_ListaDispositivosPosicion(global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosPosicionRequest request) {
            return base.Channel.SP_ListaDispositivosPosicion(request);
        }
        
        public System.Xml.Linq.XElement SP_ListaDispositivosPosicion() {
            global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosPosicionRequest inValue = new global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosPosicionRequest();
            inValue.Body = new global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosPosicionRequestBody();
            global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosPosicionResponse retVal = ((global::demoCalculoDetenido.wcfGps.IService1)(this)).SP_ListaDispositivosPosicion(inValue);
            return retVal.Body.SP_ListaDispositivosPosicionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosPosicionResponse> global::demoCalculoDetenido.wcfGps.IService1.SP_ListaDispositivosPosicionAsync(global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosPosicionRequest request) {
            return base.Channel.SP_ListaDispositivosPosicionAsync(request);
        }
        
        public System.Threading.Tasks.Task<global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosPosicionResponse> SP_ListaDispositivosPosicionAsync() {
            global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosPosicionRequest inValue = new global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosPosicionRequest();
            inValue.Body = new global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosPosicionRequestBody();
            return ((global::demoCalculoDetenido.wcfGps.IService1)(this)).SP_ListaDispositivosPosicionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosPosicionIdResponse global::demoCalculoDetenido.wcfGps.IService1.SP_ListaDispositivosPosicionId(global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosPosicionIdRequest request) {
            return base.Channel.SP_ListaDispositivosPosicionId(request);
        }
        
        public System.Xml.Linq.XElement SP_ListaDispositivosPosicionId(int id) {
            global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosPosicionIdRequest inValue = new global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosPosicionIdRequest();
            inValue.Body = new global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosPosicionIdRequestBody();
            inValue.Body.id = id;
            global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosPosicionIdResponse retVal = ((global::demoCalculoDetenido.wcfGps.IService1)(this)).SP_ListaDispositivosPosicionId(inValue);
            return retVal.Body.SP_ListaDispositivosPosicionIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosPosicionIdResponse> global::demoCalculoDetenido.wcfGps.IService1.SP_ListaDispositivosPosicionIdAsync(global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosPosicionIdRequest request) {
            return base.Channel.SP_ListaDispositivosPosicionIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosPosicionIdResponse> SP_ListaDispositivosPosicionIdAsync(int id) {
            global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosPosicionIdRequest inValue = new global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosPosicionIdRequest();
            inValue.Body = new global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosPosicionIdRequestBody();
            inValue.Body.id = id;
            return ((global::demoCalculoDetenido.wcfGps.IService1)(this)).SP_ListaDispositivosPosicionIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosResponse global::demoCalculoDetenido.wcfGps.IService1.SP_ListaDispositivos(global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosRequest request) {
            return base.Channel.SP_ListaDispositivos(request);
        }
        
        public System.Xml.Linq.XElement SP_ListaDispositivos() {
            global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosRequest inValue = new global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosRequest();
            inValue.Body = new global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosRequestBody();
            global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosResponse retVal = ((global::demoCalculoDetenido.wcfGps.IService1)(this)).SP_ListaDispositivos(inValue);
            return retVal.Body.SP_ListaDispositivosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosResponse> global::demoCalculoDetenido.wcfGps.IService1.SP_ListaDispositivosAsync(global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosRequest request) {
            return base.Channel.SP_ListaDispositivosAsync(request);
        }
        
        public System.Threading.Tasks.Task<global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosResponse> SP_ListaDispositivosAsync() {
            global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosRequest inValue = new global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosRequest();
            inValue.Body = new global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosRequestBody();
            return ((global::demoCalculoDetenido.wcfGps.IService1)(this)).SP_ListaDispositivosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosIDResponse global::demoCalculoDetenido.wcfGps.IService1.SP_ListaDispositivosID(global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosIDRequest request) {
            return base.Channel.SP_ListaDispositivosID(request);
        }
        
        public System.Xml.Linq.XElement SP_ListaDispositivosID(int id) {
            global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosIDRequest inValue = new global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosIDRequest();
            inValue.Body = new global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosIDRequestBody();
            inValue.Body.id = id;
            global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosIDResponse retVal = ((global::demoCalculoDetenido.wcfGps.IService1)(this)).SP_ListaDispositivosID(inValue);
            return retVal.Body.SP_ListaDispositivosIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosIDResponse> global::demoCalculoDetenido.wcfGps.IService1.SP_ListaDispositivosIDAsync(global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosIDRequest request) {
            return base.Channel.SP_ListaDispositivosIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosIDResponse> SP_ListaDispositivosIDAsync(int id) {
            global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosIDRequest inValue = new global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosIDRequest();
            inValue.Body = new global::demoCalculoDetenido.wcfGps.SP_ListaDispositivosIDRequestBody();
            inValue.Body.id = id;
            return ((global::demoCalculoDetenido.wcfGps.IService1)(this)).SP_ListaDispositivosIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::demoCalculoDetenido.wcfGps.SP_GetColoresResponse global::demoCalculoDetenido.wcfGps.IService1.SP_GetColores(global::demoCalculoDetenido.wcfGps.SP_GetColoresRequest request) {
            return base.Channel.SP_GetColores(request);
        }
        
        public System.Xml.Linq.XElement SP_GetColores() {
            global::demoCalculoDetenido.wcfGps.SP_GetColoresRequest inValue = new global::demoCalculoDetenido.wcfGps.SP_GetColoresRequest();
            inValue.Body = new global::demoCalculoDetenido.wcfGps.SP_GetColoresRequestBody();
            global::demoCalculoDetenido.wcfGps.SP_GetColoresResponse retVal = ((global::demoCalculoDetenido.wcfGps.IService1)(this)).SP_GetColores(inValue);
            return retVal.Body.SP_GetColoresResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<global::demoCalculoDetenido.wcfGps.SP_GetColoresResponse> global::demoCalculoDetenido.wcfGps.IService1.SP_GetColoresAsync(global::demoCalculoDetenido.wcfGps.SP_GetColoresRequest request) {
            return base.Channel.SP_GetColoresAsync(request);
        }
        
        public System.Threading.Tasks.Task<global::demoCalculoDetenido.wcfGps.SP_GetColoresResponse> SP_GetColoresAsync() {
            global::demoCalculoDetenido.wcfGps.SP_GetColoresRequest inValue = new global::demoCalculoDetenido.wcfGps.SP_GetColoresRequest();
            inValue.Body = new global::demoCalculoDetenido.wcfGps.SP_GetColoresRequestBody();
            return ((global::demoCalculoDetenido.wcfGps.IService1)(this)).SP_GetColoresAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::demoCalculoDetenido.wcfGps.SP_GetColoresIDResponse global::demoCalculoDetenido.wcfGps.IService1.SP_GetColoresID(global::demoCalculoDetenido.wcfGps.SP_GetColoresIDRequest request) {
            return base.Channel.SP_GetColoresID(request);
        }
        
        public System.Xml.Linq.XElement SP_GetColoresID(int id) {
            global::demoCalculoDetenido.wcfGps.SP_GetColoresIDRequest inValue = new global::demoCalculoDetenido.wcfGps.SP_GetColoresIDRequest();
            inValue.Body = new global::demoCalculoDetenido.wcfGps.SP_GetColoresIDRequestBody();
            inValue.Body.id = id;
            global::demoCalculoDetenido.wcfGps.SP_GetColoresIDResponse retVal = ((global::demoCalculoDetenido.wcfGps.IService1)(this)).SP_GetColoresID(inValue);
            return retVal.Body.SP_GetColoresIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<global::demoCalculoDetenido.wcfGps.SP_GetColoresIDResponse> global::demoCalculoDetenido.wcfGps.IService1.SP_GetColoresIDAsync(global::demoCalculoDetenido.wcfGps.SP_GetColoresIDRequest request) {
            return base.Channel.SP_GetColoresIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<global::demoCalculoDetenido.wcfGps.SP_GetColoresIDResponse> SP_GetColoresIDAsync(int id) {
            global::demoCalculoDetenido.wcfGps.SP_GetColoresIDRequest inValue = new global::demoCalculoDetenido.wcfGps.SP_GetColoresIDRequest();
            inValue.Body = new global::demoCalculoDetenido.wcfGps.SP_GetColoresIDRequestBody();
            inValue.Body.id = id;
            return ((global::demoCalculoDetenido.wcfGps.IService1)(this)).SP_GetColoresIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::demoCalculoDetenido.wcfGps.WPL_POW_EntregaRetiroResponse global::demoCalculoDetenido.wcfGps.IService1.WPL_POW_EntregaRetiro(global::demoCalculoDetenido.wcfGps.WPL_POW_EntregaRetiroRequest request) {
            return base.Channel.WPL_POW_EntregaRetiro(request);
        }
        
        public System.Xml.Linq.XElement WPL_POW_EntregaRetiro(string contrato, string rut) {
            global::demoCalculoDetenido.wcfGps.WPL_POW_EntregaRetiroRequest inValue = new global::demoCalculoDetenido.wcfGps.WPL_POW_EntregaRetiroRequest();
            inValue.Body = new global::demoCalculoDetenido.wcfGps.WPL_POW_EntregaRetiroRequestBody();
            inValue.Body.contrato = contrato;
            inValue.Body.rut = rut;
            global::demoCalculoDetenido.wcfGps.WPL_POW_EntregaRetiroResponse retVal = ((global::demoCalculoDetenido.wcfGps.IService1)(this)).WPL_POW_EntregaRetiro(inValue);
            return retVal.Body.WPL_POW_EntregaRetiroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<global::demoCalculoDetenido.wcfGps.WPL_POW_EntregaRetiroResponse> global::demoCalculoDetenido.wcfGps.IService1.WPL_POW_EntregaRetiroAsync(global::demoCalculoDetenido.wcfGps.WPL_POW_EntregaRetiroRequest request) {
            return base.Channel.WPL_POW_EntregaRetiroAsync(request);
        }
        
        public System.Threading.Tasks.Task<global::demoCalculoDetenido.wcfGps.WPL_POW_EntregaRetiroResponse> WPL_POW_EntregaRetiroAsync(string contrato, string rut) {
            global::demoCalculoDetenido.wcfGps.WPL_POW_EntregaRetiroRequest inValue = new global::demoCalculoDetenido.wcfGps.WPL_POW_EntregaRetiroRequest();
            inValue.Body = new global::demoCalculoDetenido.wcfGps.WPL_POW_EntregaRetiroRequestBody();
            inValue.Body.contrato = contrato;
            inValue.Body.rut = rut;
            return ((global::demoCalculoDetenido.wcfGps.IService1)(this)).WPL_POW_EntregaRetiroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::demoCalculoDetenido.wcfGps.SP_TraePosicionesResponse global::demoCalculoDetenido.wcfGps.IService1.SP_TraePosiciones(global::demoCalculoDetenido.wcfGps.SP_TraePosicionesRequest request) {
            return base.Channel.SP_TraePosiciones(request);
        }
        
        public System.Xml.Linq.XElement SP_TraePosiciones(int id, string fechain, string fechaout) {
            global::demoCalculoDetenido.wcfGps.SP_TraePosicionesRequest inValue = new global::demoCalculoDetenido.wcfGps.SP_TraePosicionesRequest();
            inValue.Body = new global::demoCalculoDetenido.wcfGps.SP_TraePosicionesRequestBody();
            inValue.Body.id = id;
            inValue.Body.fechain = fechain;
            inValue.Body.fechaout = fechaout;
            global::demoCalculoDetenido.wcfGps.SP_TraePosicionesResponse retVal = ((global::demoCalculoDetenido.wcfGps.IService1)(this)).SP_TraePosiciones(inValue);
            return retVal.Body.SP_TraePosicionesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<global::demoCalculoDetenido.wcfGps.SP_TraePosicionesResponse> global::demoCalculoDetenido.wcfGps.IService1.SP_TraePosicionesAsync(global::demoCalculoDetenido.wcfGps.SP_TraePosicionesRequest request) {
            return base.Channel.SP_TraePosicionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<global::demoCalculoDetenido.wcfGps.SP_TraePosicionesResponse> SP_TraePosicionesAsync(int id, string fechain, string fechaout) {
            global::demoCalculoDetenido.wcfGps.SP_TraePosicionesRequest inValue = new global::demoCalculoDetenido.wcfGps.SP_TraePosicionesRequest();
            inValue.Body = new global::demoCalculoDetenido.wcfGps.SP_TraePosicionesRequestBody();
            inValue.Body.id = id;
            inValue.Body.fechain = fechain;
            inValue.Body.fechaout = fechaout;
            return ((global::demoCalculoDetenido.wcfGps.IService1)(this)).SP_TraePosicionesAsync(inValue);
        }
        
        public string SP_UpdateDispositivo(int id, string nombre, string modelo, string patente, string imei, string numero, int activo, int color) {
            return base.Channel.SP_UpdateDispositivo(id, nombre, modelo, patente, imei, numero, activo, color);
        }
        
        public System.Threading.Tasks.Task<string> SP_UpdateDispositivoAsync(int id, string nombre, string modelo, string patente, string imei, string numero, int activo, int color) {
            return base.Channel.SP_UpdateDispositivoAsync(id, nombre, modelo, patente, imei, numero, activo, color);
        }
        
        public string SP_InsertaDispositivo(string nombre, string modelo, string patente, string imei, string numero, int activo, int color) {
            return base.Channel.SP_InsertaDispositivo(nombre, modelo, patente, imei, numero, activo, color);
        }
        
        public System.Threading.Tasks.Task<string> SP_InsertaDispositivoAsync(string nombre, string modelo, string patente, string imei, string numero, int activo, int color) {
            return base.Channel.SP_InsertaDispositivoAsync(nombre, modelo, patente, imei, numero, activo, color);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::demoCalculoDetenido.wcfGps.SP_MarcaAlarmaResponse global::demoCalculoDetenido.wcfGps.IService1.SP_MarcaAlarma(global::demoCalculoDetenido.wcfGps.SP_MarcaAlarmaRequest request) {
            return base.Channel.SP_MarcaAlarma(request);
        }
        
        public System.Xml.Linq.XElement SP_MarcaAlarma(int id) {
            global::demoCalculoDetenido.wcfGps.SP_MarcaAlarmaRequest inValue = new global::demoCalculoDetenido.wcfGps.SP_MarcaAlarmaRequest();
            inValue.Body = new global::demoCalculoDetenido.wcfGps.SP_MarcaAlarmaRequestBody();
            inValue.Body.id = id;
            global::demoCalculoDetenido.wcfGps.SP_MarcaAlarmaResponse retVal = ((global::demoCalculoDetenido.wcfGps.IService1)(this)).SP_MarcaAlarma(inValue);
            return retVal.Body.SP_MarcaAlarmaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<global::demoCalculoDetenido.wcfGps.SP_MarcaAlarmaResponse> global::demoCalculoDetenido.wcfGps.IService1.SP_MarcaAlarmaAsync(global::demoCalculoDetenido.wcfGps.SP_MarcaAlarmaRequest request) {
            return base.Channel.SP_MarcaAlarmaAsync(request);
        }
        
        public System.Threading.Tasks.Task<global::demoCalculoDetenido.wcfGps.SP_MarcaAlarmaResponse> SP_MarcaAlarmaAsync(int id) {
            global::demoCalculoDetenido.wcfGps.SP_MarcaAlarmaRequest inValue = new global::demoCalculoDetenido.wcfGps.SP_MarcaAlarmaRequest();
            inValue.Body = new global::demoCalculoDetenido.wcfGps.SP_MarcaAlarmaRequestBody();
            inValue.Body.id = id;
            return ((global::demoCalculoDetenido.wcfGps.IService1)(this)).SP_MarcaAlarmaAsync(inValue);
        }
        
        public string SP_InsertaPosicion(string direccion, double altitud, double curso, double latitud, double longitud, string otros, int poder, double velocidad, System.DateTime fechahora, int valido, int dispositivo_id) {
            return base.Channel.SP_InsertaPosicion(direccion, altitud, curso, latitud, longitud, otros, poder, velocidad, fechahora, valido, dispositivo_id);
        }
        
        public System.Threading.Tasks.Task<string> SP_InsertaPosicionAsync(string direccion, double altitud, double curso, double latitud, double longitud, string otros, int poder, double velocidad, System.DateTime fechahora, int valido, int dispositivo_id) {
            return base.Channel.SP_InsertaPosicionAsync(direccion, altitud, curso, latitud, longitud, otros, poder, velocidad, fechahora, valido, dispositivo_id);
        }
    }
}
